# Tensor Manipulation

### Imports

In [4]:
import numpy as np
import torch

### 1. Tensor in PyTorch

+ Tensor?
  - Vector (Rank = 1)

	$$
	\begin{bmatrix} 
	1 & 2 & 3 \\
	\end{bmatrix}
	\quad
	$$

  - Matrix (Rank = 2)
	$$
	\begin{bmatrix} 
	1 & 2 & 3 \\
  4 & 5 & 6 \\
	\end{bmatrix}
	\quad
	$$

  - Tensor (Rank > 2)
    * 2D 화면에 표현하기 어렵다
    * 머리속에 상상 가능하지만 개인차가 있음
  - rank, shape, axis에 관한 수학적 정의를 시간날 때 마다 복습해 두는 것을 추천
  - 관련 유튜브 영상도 많다

In [5]:
# Numpy와 비슷한 문법
tensor = torch.FloatTensor([1, 2, 3, 4])
print(tensor)  # tensor 출력
print(tensor.shape)   # tensor의 shape 출력
print(tensor[1:3])    # tensor slicing

tensor([1., 2., 3., 4.])
torch.Size([4])
tensor([2., 3.])


In [6]:
# 3차원 이상
tensor3d = torch.FloatTensor([[[1, 2, 3, 4], 
                                [5, 6, 7, 8],
                                [9, 10, 11, 12]],
                              
                               [[13, 14, 15, 16],
                                [17, 18, 19, 20],
                                [21, 22, 23, 24]]])
print(tensor3d)   # tensor3d 출력
print(tensor3d.shape)   # tensro3d의 shape 출력

tensor([[[ 1.,  2.,  3.,  4.],
         [ 5.,  6.,  7.,  8.],
         [ 9., 10., 11., 12.]],

        [[13., 14., 15., 16.],
         [17., 18., 19., 20.],
         [21., 22., 23., 24.]]])
torch.Size([2, 3, 4])


### 2. Tensor Combinations

- Concatenation
  + 경계를 무너뜨리며 붙인다

  $$
	\begin{bmatrix} 
	1 & 2 \\
  3 & 4 \\
	\end{bmatrix}
	\quad
  (·)
  \quad
  \begin{bmatrix} 
	5 & 6 \\
  7 & 8 \\
	\end{bmatrix}
	\quad
  \rightarrow
  \quad
  \begin{bmatrix} 
	1 & 2 & 5 & 6 \\
  3 & 4 & 7 & 8 \\
	\end{bmatrix}
	\quad
	$$

In [7]:
x = torch.FloatTensor([[1, 2], [3, 4]])
y = torch.FloatTensor([[5, 6], [7, 8]])
print(x)
print(y)
print(torch.cat([x,y], dim = 0))
print(torch.cat([x,y], dim = 1))

tensor([[1., 2.],
        [3., 4.]])
tensor([[5., 6.],
        [7., 8.]])
tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])
tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]])


- Stack
  + 경계를 구분한 채로 붙인다

  $$
	\begin{bmatrix} 
	1 & 2 \\
  3 & 4 \\
	\end{bmatrix}
	\quad
  (*)
  \quad
  \begin{bmatrix} 
	5 & 6 \\
  7 & 8 \\
	\end{bmatrix}
	\quad
  \rightarrow
  \quad
  \begin{bmatrix}
  \begin{bmatrix} 
	1 & 2 \\
  3 & 4 \\
	\end{bmatrix}
  \quad
  \begin{bmatrix} 
	5 & 6 \\
  7 & 8 \\
	\end{bmatrix}
  \end{bmatrix}
	\quad
	$$

In [8]:
print(torch.stack([x,y], dim = 0))
print(torch.stack([x,y], dim = 1))

tensor([[[1., 2.],
         [3., 4.]],

        [[5., 6.],
         [7., 8.]]])
tensor([[[1., 2.],
         [5., 6.]],

        [[3., 4.],
         [7., 8.]]])


- View / Reshape
  + data를 유지한 채 shape을 변형한다
    * Pointer를 반환하므로 원본을 훼손하지 않으려면 복사본을 이용한다

In [9]:
x = torch.rand(2, 3, 4)  # [2, 3, 4] 
y = x.view(2, -1)  # [2, 12] 
z = x.reshape(2, -1) # [2, 12]
print(x)
print(y)
print(z)
z[0] = 0.0
print(x)

tensor([[[0.8297, 0.8591, 0.7735, 0.3655],
         [0.3587, 0.8606, 0.7557, 0.2772],
         [0.7805, 0.8613, 0.4074, 0.9981]],

        [[0.2399, 0.4030, 0.1161, 0.2514],
         [0.1933, 0.0112, 0.9694, 0.7929],
         [0.4007, 0.6157, 0.4498, 0.8142]]])
tensor([[0.8297, 0.8591, 0.7735, 0.3655, 0.3587, 0.8606, 0.7557, 0.2772, 0.7805,
         0.8613, 0.4074, 0.9981],
        [0.2399, 0.4030, 0.1161, 0.2514, 0.1933, 0.0112, 0.9694, 0.7929, 0.4007,
         0.6157, 0.4498, 0.8142]])
tensor([[0.8297, 0.8591, 0.7735, 0.3655, 0.3587, 0.8606, 0.7557, 0.2772, 0.7805,
         0.8613, 0.4074, 0.9981],
        [0.2399, 0.4030, 0.1161, 0.2514, 0.1933, 0.0112, 0.9694, 0.7929, 0.4007,
         0.6157, 0.4498, 0.8142]])
tensor([[[0.0000, 0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000, 0.0000]],

        [[0.2399, 0.4030, 0.1161, 0.2514],
         [0.1933, 0.0112, 0.9694, 0.7929],
         [0.4007, 0.6157, 0.4498, 0.8142]]])


- Squeeze
  + 불필요한 rank를 줄인다

In [10]:
_data = np.array([1,2,3,4])
x = torch.from_numpy(_data)
print(x)
print(x.T)
_data = np.array([_data])
x = torch.from_numpy(_data)
print(x)
print(x.T)
print(x.T.squeeze())

tensor([1, 2, 3, 4])
tensor([1, 2, 3, 4])
tensor([[1, 2, 3, 4]])
tensor([[1],
        [2],
        [3],
        [4]])
tensor([1, 2, 3, 4])


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: UserWarning: The use of `x.T` on tensors of dimension other than 2 to reverse their shape is deprecated and it will throw an error in a future release. Consider `x.mT` to transpose batches of matricesor `x.permute(*torch.arange(x.ndim - 1, -1, -1))` to reverse the dimensions of a tensor. (Triggered internally at  ../aten/src/ATen/native/TensorShape.cpp:2981.)
  after removing the cwd from sys.path.


### 3. Tensor Operations

- 사칙연산 - 요소별(Element-wise) 연산

In [11]:
# 요소별 곱셈
print(tensor)
print(tensor3d)
print(tensor * tensor3d)

tensor([1., 2., 3., 4.])
tensor([[[ 1.,  2.,  3.,  4.],
         [ 5.,  6.,  7.,  8.],
         [ 9., 10., 11., 12.]],

        [[13., 14., 15., 16.],
         [17., 18., 19., 20.],
         [21., 22., 23., 24.]]])
tensor([[[ 1.,  4.,  9., 16.],
         [ 5., 12., 21., 32.],
         [ 9., 20., 33., 48.]],

        [[13., 28., 45., 64.],
         [17., 36., 57., 80.],
         [21., 44., 69., 96.]]])


In [12]:
# 상수 덧셈
print(tensor3d + 3)

tensor([[[ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.]],

        [[16., 17., 18., 19.],
         [20., 21., 22., 23.],
         [24., 25., 26., 27.]]])


In [13]:
# tensor 덧셈
tensor_a = torch.FloatTensor([1, 2, 3, 4])
tensor_b = torch.FloatTensor([[1], [2], [3]])
tensor_c = torch.FloatTensor([[[1]],[[2]]])
print(tensor3d)
print(tensor3d + tensor_a)
print(tensor3d + tensor_b)
print(tensor3d + tensor_c)

tensor([[[ 1.,  2.,  3.,  4.],
         [ 5.,  6.,  7.,  8.],
         [ 9., 10., 11., 12.]],

        [[13., 14., 15., 16.],
         [17., 18., 19., 20.],
         [21., 22., 23., 24.]]])
tensor([[[ 2.,  4.,  6.,  8.],
         [ 6.,  8., 10., 12.],
         [10., 12., 14., 16.]],

        [[14., 16., 18., 20.],
         [18., 20., 22., 24.],
         [22., 24., 26., 28.]]])
tensor([[[ 2.,  3.,  4.,  5.],
         [ 7.,  8.,  9., 10.],
         [12., 13., 14., 15.]],

        [[14., 15., 16., 17.],
         [19., 20., 21., 22.],
         [24., 25., 26., 27.]]])
tensor([[[ 2.,  3.,  4.,  5.],
         [ 6.,  7.,  8.,  9.],
         [10., 11., 12., 13.]],

        [[15., 16., 17., 18.],
         [19., 20., 21., 22.],
         [23., 24., 25., 26.]]])


- Tensor transpose
  + shape(2, 3, 4) >> shape(4, 3, 2)
  + 3차원의 경우, 머릿속으로 상상하기 힘들다

In [14]:
print(tensor3d)
print(tensor3d.T)

tensor([[[ 1.,  2.,  3.,  4.],
         [ 5.,  6.,  7.,  8.],
         [ 9., 10., 11., 12.]],

        [[13., 14., 15., 16.],
         [17., 18., 19., 20.],
         [21., 22., 23., 24.]]])
tensor([[[ 1., 13.],
         [ 5., 17.],
         [ 9., 21.]],

        [[ 2., 14.],
         [ 6., 18.],
         [10., 22.]],

        [[ 3., 15.],
         [ 7., 19.],
         [11., 23.]],

        [[ 4., 16.],
         [ 8., 20.],
         [12., 24.]]])


- Tensor dot product
  + 마찬가지로 3차원의 경우, 머릿속으로 상상하기 힘들기 때문에 수식에 오류가 없음을 반드시 확인해야 한다
  + shape(2,3,4) * shape(4) >> shape(2,3)

In [15]:
print(tensor3d.matmul(tensor))

tensor([[ 30.,  70., 110.],
        [150., 190., 230.]])


- Mean, Sum, Max

In [16]:
print(tensor3d)
print(tensor3d.mean())
print(tensor3d.shape)
print(tensor3d.mean(dim=0))
print(tensor3d.mean(dim=1))
print(tensor3d.mean(dim=2))

tensor([[[ 1.,  2.,  3.,  4.],
         [ 5.,  6.,  7.,  8.],
         [ 9., 10., 11., 12.]],

        [[13., 14., 15., 16.],
         [17., 18., 19., 20.],
         [21., 22., 23., 24.]]])
tensor(12.5000)
torch.Size([2, 3, 4])
tensor([[ 7.,  8.,  9., 10.],
        [11., 12., 13., 14.],
        [15., 16., 17., 18.]])
tensor([[ 5.,  6.,  7.,  8.],
        [17., 18., 19., 20.]])
tensor([[ 2.5000,  6.5000, 10.5000],
        [14.5000, 18.5000, 22.5000]])


In [17]:
print(tensor3d.sum())
print(tensor3d.sum(dim=0))

tensor(300.)
tensor([[14., 16., 18., 20.],
        [22., 24., 26., 28.],
        [30., 32., 34., 36.]])


In [18]:
print(tensor3d.max())
print(tensor3d.max(dim=1))
values, indices = tensor3d.max(dim=1)
print(values)

tensor(24.)
torch.return_types.max(
values=tensor([[ 9., 10., 11., 12.],
        [21., 22., 23., 24.]]),
indices=tensor([[2, 2, 2, 2],
        [2, 2, 2, 2]]))
tensor([[ 9., 10., 11., 12.],
        [21., 22., 23., 24.]])


- 역행렬

In [19]:
tensor_square = torch.FloatTensor([[1, 7], [-4, 6]])
print(torch.inverse(tensor_square))

tensor([[ 0.1765, -0.2059],
        [ 0.1176,  0.0294]])


### 4. 실습 (Assignment 6)
- 행렬 방정식 풀기 (단, PyTorch만을 사용한다)
  + 다음 행렬방정식을 'Pseudo inverse matrix'를 이용해 풀어보자
  + $A^TA$의 역행렬이 존재한다고 가정
  $$
  Ax = B
  $$

  $$
  A =
	\begin{bmatrix} 
	0 && 1 \\
  1 && 1 \\
  2 && 1 \\
  3 && 1 \\
	\end{bmatrix}
	$$

  $$
  B = 
  \begin{bmatrix} 
	-1 \\
  0.2 \\
  0.9 \\
  2.1 \\
	\end{bmatrix}
  $$

In [20]:
# imports
import numpy as np
import torch
import torch.linalg as lin

# Tensor 입력
# 해가 되는 x는 empty tensor로 지정
mat_a = torch.FloatTensor([[0, 1],
                          [1, 1],
                          [2, 1],
                          [3, 1]])

mat_x = torch.FloatTensor([[],
                          [],
                          [],
                          []])

mat_b = torch.FloatTensor([[-1],
                          [0.2],
                          [0.9],
                          [2.1]])

# Tensor 확인
print(mat_a)
print(mat_x)
print(mat_b)

# inverse A
pinv_a = lin.pinv(mat_a)
print(pinv_a)

# B reshape
reshaped_b = torch.FloatTensor(mat_b).reshape(4,1)
print(reshaped_b)

# Tensor 연산
mat_x = torch.matmul(pinv_a, reshaped_b)

# 결과 출력
print(mat_x)

tensor([[0., 1.],
        [1., 1.],
        [2., 1.],
        [3., 1.]])
tensor([], size=(4, 0))
tensor([[-1.0000],
        [ 0.2000],
        [ 0.9000],
        [ 2.1000]])
tensor([[-0.3000, -0.1000,  0.1000,  0.3000],
        [ 0.7000,  0.4000,  0.1000, -0.2000]])
tensor([[-1.0000],
        [ 0.2000],
        [ 0.9000],
        [ 2.1000]])
tensor([[ 1.0000],
        [-0.9500]])
